#!/usr/bin/env python3
"""Packs reviewed 256px page photos into 1024x1024 sprite atlases (16 per atlas) and writes
src/server/Images/Manifest.luau plus assets/images/CREDITS.md.

Usage: python build_atlases.py <photos_dir>   (photos_dir has index.json from tools/wiki/zim_photos.py)
Photos listed in tools/images/rejected.txt (one title per line) are never packed.
"""
import json, os, sys
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..", "..")
OUT_DIR = os.path.join(ROOT, "assets", "images")
MANIFEST = os.path.join(ROOT, "src", "server", "Images", "Manifest.luau")
TILE, PER_ROW, PER_ATLAS = 256, 4, 16


def luau_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    photos_dir = sys.argv[1]
    index = json.load(open(os.path.join(photos_dir, "index.json")))
    rejected = set()
    path = os.path.join(HERE, "rejected.txt")
    if os.path.exists(path):
        rejected = {line.strip() for line in open(path) if line.strip() and not line.startswith("#")}
    titles = sorted(t for t in index if t not in rejected)
    os.makedirs(OUT_DIR, exist_ok=True)
    for f in os.listdir(OUT_DIR):
        if f.startswith("atlas_"):
            os.remove(os.path.join(OUT_DIR, f))
    lines = ["-- Page title → photo tile (atlas index, slot 1-16) and credit.",
             "-- Generated by tools/images/build_atlases.py from human-reviewed Wikimedia Commons images.",
             "return {", "\ttileSize = %d," % TILE, "\tperRow = %d," % PER_ROW, "\tphotos = {"]
    credits = ["# Photo credits", "", "Page photos are downscaled from files on Wikimedia Commons, used under their",
               "free licenses (CC BY / CC BY-SA / public domain). Each file page on commons.wikimedia.org lists",
               "its author and exact license.", "", "| Page | Commons file |", "|---|---|"]
    atlas = None
    for i, title in enumerate(titles):
        a, slot = i // PER_ATLAS + 1, i % PER_ATLAS
        if slot == 0:
            if atlas:
                atlas.save(os.path.join(OUT_DIR, "atlas_%03d.jpg" % (a - 1)), "JPEG", quality=82)
            atlas = Image.new("RGB", (TILE * PER_ROW, TILE * PER_ROW), (32, 32, 32))
        im = Image.open(os.path.join(photos_dir, index[title]["jpg"])).convert("RGB").resize((TILE, TILE))
        atlas.paste(im, ((slot % PER_ROW) * TILE, (slot // PER_ROW) * TILE))
        credit = "Wikimedia Commons: " + index[title]["file"]
        lines.append("\t\t[%s] = { atlas = %d, slot = %d, credit = %s }," % (luau_str(title), a, slot + 1, luau_str(credit[:120])))
        credits.append("| %s | %s |" % (title.replace("|", "/"), index[title]["file"].replace("|", "/")))
    if atlas:
        atlas.save(os.path.join(OUT_DIR, "atlas_%03d.jpg" % ((len(titles) - 1) // PER_ATLAS + 1)), "JPEG", quality=82)
    lines += ["\t},", "}"]
    open(MANIFEST, "w").write("\n".join(lines) + "\n")
    open(os.path.join(OUT_DIR, "CREDITS.md"), "w").write("\n".join(credits) + "\n")
    print("%d photos → %d atlases (%d rejected)" % (len(titles), (len(titles) + PER_ATLAS - 1) // PER_ATLAS, len(rejected)))


if __name__ == "__main__":
    main()
