// Roblox Enum items with their serialized integer values.
//
// XML model/place files store enums as `<token>` integers, so these values
// must be exact. Only enums used by properties in classes.ts are listed.

export const ENUMS: Record<string, Record<string, number>> = {
  Material: {
    Plastic: 256,
    SmoothPlastic: 272,
    Neon: 288,
    Wood: 512,
    WoodPlanks: 528,
    Marble: 784,
    Basalt: 788,
    Slate: 800,
    CrackedLava: 804,
    Concrete: 816,
    Limestone: 820,
    Granite: 832,
    Pavement: 836,
    Brick: 848,
    Pebble: 864,
    Cobblestone: 880,
    Rock: 896,
    Sandstone: 912,
    CorrodedMetal: 1040,
    DiamondPlate: 1056,
    Foil: 1072,
    Metal: 1088,
    Grass: 1280,
    LeafyGrass: 1284,
    Sand: 1296,
    Fabric: 1312,
    Snow: 1328,
    Mud: 1344,
    Ground: 1360,
    Asphalt: 1376,
    Salt: 1392,
    Ice: 1536,
    Glacier: 1552,
    Glass: 1568,
    ForceField: 1584,
    Air: 1792,
    Water: 2048,
  },
  PartType: { Ball: 0, Block: 1, Cylinder: 2, Wedge: 3, CornerWedge: 4 },
  SurfaceType: { Smooth: 0, Glue: 1, Weld: 2, Studs: 3, Inlet: 4, Universal: 5, Hinge: 6, Motor: 7, SteppingMotor: 8, SmoothNoOutlines: 10 },
  NormalId: { Right: 0, Top: 1, Back: 2, Left: 3, Bottom: 4, Front: 5 },
  TextXAlignment: { Left: 0, Right: 1, Center: 2 },
  TextYAlignment: { Top: 0, Center: 1, Bottom: 2 },
  TextTruncate: { None: 0, AtEnd: 1, SplitWord: 2 },
  FillDirection: { Horizontal: 0, Vertical: 1 },
  HorizontalAlignment: { Center: 0, Left: 1, Right: 2 },
  VerticalAlignment: { Center: 0, Top: 1, Bottom: 2 },
  SortOrder: { Name: 0, Custom: 1, LayoutOrder: 2 },
  StartCorner: { TopLeft: 0, TopRight: 1, BottomLeft: 2, BottomRight: 3 },
  ZIndexBehavior: { Global: 0, Sibling: 1 },
  AutomaticSize: { None: 0, X: 1, Y: 2, XY: 3 },
  ApplyStrokeMode: { Contextual: 0, Border: 1 },
  LineJoinMode: { Round: 0, Bevel: 1, Miter: 2 },
  ScaleType: { Stretch: 0, Slice: 1, Tile: 2, Fit: 3, Crop: 4 },
  ScrollingDirection: { X: 1, Y: 2, XY: 4 },
  ElasticBehavior: { WhenScrollable: 0, Always: 1, Never: 2 },
  AspectType: { FitWithinMaxSize: 0, ScaleWithParentSize: 1 },
  DominantAxis: { Width: 0, Height: 1 },
  SizeConstraint: { RelativeXY: 0, RelativeXX: 1, RelativeYY: 2 },
  BorderMode: { Outline: 0, Middle: 1, Inset: 2 },
  ResamplerMode: { Default: 0, Pixelated: 1 },
  ScreenInsets: { None: 0, DeviceSafeInsets: 1, CoreUISafeInsets: 2, TopbarSafeInsets: 3 },
  RunContext: { Legacy: 0, Server: 1, Client: 2, Plugin: 3 },
  HumanoidRigType: { R6: 0, R15: 1 },
  HumanoidDisplayDistanceType: { Viewer: 0, Subject: 1, None: 2 },
  ProximityPromptStyle: { Default: 0, Custom: 1 },
  ProximityPromptExclusivity: { OnePerButton: 0, OneGlobally: 1, AlwaysShow: 2 },
  ParticleOrientation: { FacingCamera: 0, FacingCameraWorldUp: 1, VelocityParallel: 2, VelocityPerpendicular: 3 },
  ActuatorType: { None: 0, Motor: 1, Servo: 2 },
  ActuatorRelativeTo: { Attachment0: 0, Attachment1: 1, World: 2 },
  SurfaceGuiSizingMode: { FixedSize: 0, PixelsPerStud: 1 },
  CameraType: { Fixed: 0, Attach: 1, Watch: 2, Track: 3, Follow: 4, Custom: 5, Scriptable: 6, Orbital: 7 },
  HighlightDepthMode: { AlwaysOnTop: 0, Occluded: 1 },
  RenderFidelity: { Automatic: 0, Precise: 1, Performance: 2 },
  CollisionFidelity: { Default: 0, Hull: 1, Box: 2, PreciseConvexDecomposition: 3 },
  EasingStyle: { Linear: 0, Sine: 1, Back: 2, Quad: 3, Quart: 4, Quint: 5, Bounce: 6, Elastic: 7, Exponential: 8, Circular: 9, Cubic: 10 },
  UIFlexAlignment: { None: 0, Fill: 1, SpaceAround: 2, SpaceBetween: 3, SpaceEvenly: 4 },
  UIFlexMode: { None: 0, Grow: 1, Shrink: 2, Fill: 3, Custom: 4 },
  KeyCode: {
    Unknown: 0,
    Backspace: 8,
    Tab: 9,
    Return: 13,
    Escape: 27,
    Space: 32,
    Zero: 48,
    One: 49,
    Two: 50,
    Three: 51,
    Four: 52,
    Five: 53,
    A: 97,
    B: 98,
    C: 99,
    D: 100,
    E: 101,
    F: 102,
    G: 103,
    H: 104,
    I: 105,
    J: 106,
    K: 107,
    L: 108,
    M: 109,
    N: 110,
    O: 111,
    P: 112,
    Q: 113,
    R: 114,
    S: 115,
    T: 116,
    U: 117,
    V: 118,
    W: 119,
    X: 120,
    Y: 121,
    Z: 122,
    LeftShift: 304,
    LeftControl: 306,
    ButtonX: 1000,
    ButtonY: 1001,
    ButtonA: 1002,
    ButtonB: 1003,
  },
};

export const FONT_WEIGHTS: Record<string, number> = {
  Thin: 100,
  ExtraLight: 200,
  Light: 300,
  Regular: 400,
  Medium: 500,
  SemiBold: 600,
  Bold: 700,
  ExtraBold: 800,
  Heavy: 900,
};

/** Font families that ship with Roblox, by the name the UI shows. */
export const FONT_FAMILIES: Record<string, string> = {
  BuilderSans: "rbxasset://fonts/families/BuilderSans.json",
  GothamSSm: "rbxasset://fonts/families/GothamSSm.json",
  Montserrat: "rbxasset://fonts/families/Montserrat.json",
  SourceSansPro: "rbxasset://fonts/families/SourceSansPro.json",
  FredokaOne: "rbxasset://fonts/families/FredokaOne.json",
  Roboto: "rbxasset://fonts/families/Roboto.json",
  RobotoMono: "rbxasset://fonts/families/RobotoMono.json",
  Ubuntu: "rbxasset://fonts/families/Ubuntu.json",
  Oswald: "rbxasset://fonts/families/Oswald.json",
  Nunito: "rbxasset://fonts/families/Nunito.json",
  LuckiestGuy: "rbxasset://fonts/families/LuckiestGuy.json",
  Bangers: "rbxasset://fonts/families/Bangers.json",
  PressStart2P: "rbxasset://fonts/families/PressStart2P.json",
  Arimo: "rbxasset://fonts/families/Arimo.json",
};

/** CSS stacks used by the in-browser GUI renderer for each family. */
export const FONT_CSS: Record<string, string> = {
  BuilderSans: "'Inter', system-ui, sans-serif",
  GothamSSm: "'Montserrat', 'Inter', system-ui, sans-serif",
  Montserrat: "'Montserrat', system-ui, sans-serif",
  SourceSansPro: "'Source Sans 3', system-ui, sans-serif",
  FredokaOne: "'Fredoka', 'Nunito', system-ui, sans-serif",
  Roboto: "'Roboto', system-ui, sans-serif",
  RobotoMono: "'Roboto Mono', ui-monospace, monospace",
  Ubuntu: "'Ubuntu', system-ui, sans-serif",
  Oswald: "'Oswald', system-ui, sans-serif",
  Nunito: "'Nunito', system-ui, sans-serif",
  LuckiestGuy: "'Luckiest Guy', 'Bangers', system-ui, sans-serif",
  Bangers: "'Bangers', system-ui, sans-serif",
  PressStart2P: "'Press Start 2P', ui-monospace, monospace",
  Arimo: "'Arimo', Arial, sans-serif",
};

export function familyNameFromUrl(url: string): string {
  for (const [name, u] of Object.entries(FONT_FAMILIES)) if (u === url) return name;
  const m = /families\/([A-Za-z0-9]+)\.json/.exec(url);
  return m?.[1] ?? "BuilderSans";
}
